### ISSUE TITLE
Where is the content aware loss?

### ISSUE THREAD

**Issue by drxmy** [yxuansu/Few-Shot-Table-to-Text-Generation#1]
I can't find this content aware loss in your code. could you please tell me the corresponding code？Thank you for your time and really great work!

**Comment by yxuansu** [comment]
> I can't find this content aware loss in your code. could you please tell me the corresponding code？Thank you for your time and really great work!

Hello, thank you for your question and sorry for my late reply! We only put the base model (with only NLL loss) in this repo, because it is more stable than including the context-aware loss. We will update the code soon. The current code in the repo should give you similar results as we report in the paper.
